"""Generate structural JSON Schemas/reference from executable dataclass contracts."""
from dataclasses import fields, MISSING
from enum import Enum
from pathlib import Path
import json
import types
from typing import Union, get_args, get_origin, get_type_hints
from cognitive_runtime.adapters.finance.schemas.base import Strict, Record, VERSION
from .examples import examples
from .generate import FixtureManifest


def schema_for(kind):
    definitions = {}
    def convert(annotation):
        origin, args = get_origin(annotation), get_args(annotation)
        if origin in (Union, types.UnionType):
            return {'anyOf': [convert(x) for x in args]}
        if origin is tuple:
            return {'type': 'array', 'items': convert(args[0])}
        if isinstance(annotation, type) and issubclass(annotation, Enum):
            return {'type': 'string', 'enum': [x.value for x in annotation]}
        if isinstance(annotation, type) and issubclass(annotation, Strict):
            name = annotation.__name__
            if name not in definitions:
                definitions[name] = {}
                hints = get_type_hints(annotation)
                properties = {f.name: convert(hints[f.name]) for f in fields(annotation)}
                if issubclass(annotation, Record) or annotation is FixtureManifest:
                    properties['schema_name'] = {'const': name}
                    properties['schema_version'] = {'const': VERSION}
                definitions[name] = {'type': 'object', 'additionalProperties': False, 'properties': properties,
                                     'required': [f.name for f in fields(annotation) if f.default is MISSING and f.default_factory is MISSING]}
            return {'$ref': '#/$defs/' + name}
        return {'type': {str: 'string', int: 'integer', bool: 'boolean', type(None): 'null'}[annotation]}
    ref = convert(kind)
    return {'$schema': 'https://json-schema.org/draft/2020-12/schema', **ref, '$defs': definitions}


def render(root):
    root = Path(root)
    e = examples()
    kinds = [type(x) for x in e.values()] + [FixtureManifest]
    files = {}
    lines = ['# Generated market schema reference', '',
             'Generated by `python -m cognitive_runtime.adapters.finance.testing.document`.',
             'Structural schemas reject unknown fields; Python constructors additionally enforce',
             'decimal, clock, support and cross-field invariants. Always call the typed parser.',
             'Examples are synthetic and generated from these same constructors.', '']
    for kind in kinds:
        files[f'docs/market/schemas/{kind.__name__}.schema.json'] = json.dumps(schema_for(kind), indent=2, sort_keys=True) + '\n'
        lines.extend([f'## {kind.__name__}', '', '| Field | Type |', '| --- | --- |'])
        for name, hint in get_type_hints(kind).items():
            lines.append(f'| `{name}` | `{str(hint).replace("<class ", "").replace(">", "")}` |')
        lines.append('')
    files['docs/market/schema-reference.md'] = '\n'.join(lines)
    files['docs/market/schema-examples.json'] = json.dumps({k: v.to_dict() for k, v in e.items()}, indent=2, sort_keys=True) + '\n'
    return {root / path: contents for path, contents in files.items()}


if __name__ == '__main__':
    for path, contents in render('.') .items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents)
