"""Generative replay: dreamed old seeds mixed into new-scenario training,
gated by measured cortex quality (docs/v2/phases/phase-5-sleep-consolidation.md
task 4, issue #99). This is the mechanism the phase doc calls "the sharp
risk" and "the guardrail that makes generative replay help instead of harm":

    (a) keep a **reservoir of real transitions** and **never train on dreams
        alone**;
    (b) **gate the dream fraction on measured model quality** -- 0% until the
        cortex beats copy-last on held-out by a margin, ramp with the ratio,
        cap ~= 0.5. The dream fraction is a function of a metric, not a
        constant.

Both guardrails are enforced structurally by :class:`GenerativeReplayMixer`
rather than left to a caller's discipline: (a) is an invariant of
:meth:`GenerativeReplayMixer.mix_batch` (it always reserves at least one real
sample), and (b) is :func:`dream_fraction`, a pure function of whatever
quality signal the caller measures (e.g. :func:`copy_last_quality_margin`,
mirroring ``action_world_model.evaluate_action_world_model``'s
``model_over_copy_last_mse`` convention).

Dreams are generated by rolling a *frozen* cortex snapshot -- the
"hippocampal recall" source, distinct from the cortex actively being trained
-- forward from a stored :class:`~brain.hippocampus.Seed` via
:func:`sleep.dream.dream_latents`. Training the live cortex to reproduce a
frozen snapshot's own predictions on old seeds is what lets it rehearse a
mastered scenario without re-storing (or re-visiting) that scenario's raw
experience -- the bootstrap risk is exactly that this frozen source, not the
live model, is what dreams, so a half-trained live model drifting during new
training cannot compound errors into what it is asked to rehearse.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Any, List

import torch

from brain.hippocampus import Hippocampus, Seed
from sleep.dream import dream_latents

__all__ = [
    "dream_fraction",
    "copy_last_quality_margin",
    "ReplaySample",
    "Reservoir",
    "TrainingBatch",
    "GenerativeReplayMixer",
]


def dream_fraction(
    quality_margin: float,
    *,
    ramp_start: float = 0.0,
    ramp_end: float = 1.0,
    cap: float = 0.5,
) -> float:
    """The dream fraction as a function of measured quality, never a constant.

    ``quality_margin`` is however the caller measures "the cortex beats
    copy-last on held-out" (e.g. :func:`copy_last_quality_margin`): zero or
    negative means the cortex has not cleared the quality bar, so the
    fraction is 0.0. Above ``ramp_start`` it climbs linearly and saturates at
    ``cap`` once ``quality_margin`` reaches ``ramp_end`` -- the fraction never
    exceeds ``cap`` regardless of how large the margin gets.
    """
    if not 0.0 < cap <= 1.0:
        raise ValueError(f"cap must be in (0, 1], got {cap!r}")
    if ramp_end <= ramp_start:
        raise ValueError(
            f"ramp_end ({ramp_end!r}) must be greater than ramp_start ({ramp_start!r})"
        )
    if quality_margin <= ramp_start:
        return 0.0
    if quality_margin >= ramp_end:
        return cap
    return cap * (quality_margin - ramp_start) / (ramp_end - ramp_start)


def copy_last_quality_margin(model_mse: float, copy_last_mse: float) -> float:
    """``1 - model_mse/copy_last_mse``: positive exactly when the cortex beats
    the "copy the last latent forward" baseline, and by how much -- the same
    ``model_over_copy_last_mse`` ratio
    ``cognitive_runtime.training.action_world_model.evaluate_action_world_model``
    reports per horizon (``< 1.0`` there means "beats copy-last"), reframed as
    a margin so :func:`dream_fraction` can gate on it directly. ``copy_last_mse
    <= 0`` (a degenerate held-out set) reads as "no headroom to trust" -- 0.0,
    not a division error.
    """
    if copy_last_mse <= 0.0:
        return 0.0
    return 1.0 - (model_mse / copy_last_mse)


@dataclass(frozen=True)
class ReplaySample:
    """One cortex training sample: a starting latent, the action sequence to
    roll forward, and the target latents to fit via MSE.

    ``source`` is ``"real"`` for an actually-observed transition or
    ``"dream"`` for a frozen-snapshot rollout from a hippocampal seed --
    everything downstream (batch assembly, guardrail bookkeeping) reads this
    rather than re-deriving provenance.
    """

    z0: List[float]
    actions: List[str]
    targets: torch.Tensor  # [T, latent_width]
    source: str = "real"

    def __post_init__(self) -> None:
        if self.source not in ("real", "dream"):
            raise ValueError(f"source must be 'real' or 'dream', got {self.source!r}")
        if len(self.actions) != self.targets.shape[0]:
            raise ValueError(
                f"{len(self.actions)} actions but {self.targets.shape[0]} target latents"
            )


class Reservoir:
    """Bounded FIFO store of real cortex-training samples -- the bootstrap
    guardrail's "reservoir of real transitions". Sampling draws with
    replacement and never mutates or empties the store (docs/v2/phases/
    phase-5-sleep-consolidation.md's "reservoir retained" test): repeated
    consolidation passes keep rehearsing the same retained real experience
    rather than consuming it.
    """

    def __init__(self, capacity: int = 512):
        if capacity <= 0:
            raise ValueError(f"capacity must be positive, got {capacity!r}")
        self.capacity = capacity
        self._samples: List[ReplaySample] = []
        self._write_index = 0

    def __len__(self) -> int:
        return len(self._samples)

    def add(self, sample: ReplaySample) -> None:
        if sample.source != "real":
            raise ValueError("the reservoir only stores real transitions, not dreams")
        if len(self._samples) < self.capacity:
            self._samples.append(sample)
        else:
            self._samples[self._write_index] = sample
            self._write_index = (self._write_index + 1) % self.capacity

    def sample(self, n: int, rng: random.Random) -> List[ReplaySample]:
        if n <= 0:
            return []
        if not self._samples:
            raise ValueError("cannot sample from an empty reservoir")
        return rng.choices(self._samples, k=n)


@dataclass(frozen=True)
class TrainingBatch:
    """A stacked, ready-to-train-on minibatch plus the guardrail bookkeeping
    a caller or test needs to verify it held."""

    z0: torch.Tensor  # [B, latent_width]
    actions: torch.Tensor  # [B, T] long
    targets: torch.Tensor  # [B, T, latent_width]
    n_real: int
    n_dream: int
    fraction_requested: float

    @property
    def batch_size(self) -> int:
        return self.n_real + self.n_dream

    @property
    def fraction_actual(self) -> float:
        return self.n_dream / self.batch_size if self.batch_size else 0.0


@dataclass
class GenerativeReplayMixer:
    """Draws quality-gated, guardrailed minibatches mixing the real
    ``reservoir`` with dreams rolled from ``hippocampus`` seeds through
    ``dream_cortex`` (the frozen recall source; see module docstring).
    """

    reservoir: Reservoir
    hippocampus: Hippocampus
    dream_cortex: Any
    ramp_start: float = 0.0
    ramp_end: float = 1.0
    cap: float = 0.5
    seed: int = 0
    _rng: random.Random = field(init=False, repr=False)

    def __post_init__(self) -> None:
        self._rng = random.Random(self.seed)

    def _dream_sample(self, seed: Seed, length: int) -> ReplaySample:
        if length > len(seed.actions):
            raise ValueError(
                f"seed has {len(seed.actions)} replayable actions, fewer than "
                f"dream length {length}"
            )
        targets = dream_latents(seed, length, self.dream_cortex)
        return ReplaySample(
            z0=list(seed.z), actions=list(seed.actions[:length]), targets=targets, source="dream",
        )

    def mix_batch(
        self, batch_size: int, quality_margin: float, *, dream_length: int = 1,
    ) -> TrainingBatch:
        """One minibatch: real reservoir samples plus a quality-gated share
        of dreamed seeds, guaranteed to include at least one real sample.

        ``batch_size`` real samples are always available to fall back on
        (the reservoir is sampled with replacement), so the only two ways
        this can fail to produce a full batch are an empty reservoir (no real
        transitions to train on at all) or a hippocampus with fewer stored
        seeds than the requested dream share -- both raise rather than
        silently degrading into a smaller or dream-only batch.
        """
        if batch_size <= 0:
            raise ValueError(f"batch_size must be positive, got {batch_size!r}")
        if len(self.reservoir) == 0:
            raise ValueError("reservoir is empty: no real transitions to train on")

        fraction = dream_fraction(
            quality_margin, ramp_start=self.ramp_start, ramp_end=self.ramp_end, cap=self.cap,
        )
        # Never a dream-only batch, regardless of how the quality gate above
        # evaluates (guardrail (a)): reserve at least one real sample.
        n_dream = min(int(fraction * batch_size), batch_size - 1)
        n_real = batch_size - n_dream

        seeds = self.hippocampus.seeds()
        if n_dream > 0 and not seeds:
            n_dream = 0
            n_real = batch_size
        elif n_dream > len(seeds):
            raise ValueError(
                f"quality gate wants {n_dream} dreamed samples but the hippocampus "
                f"holds only {len(seeds)} seeds"
            )

        real_samples = self.reservoir.sample(n_real, self._rng)
        dream_seeds = self._rng.sample(seeds, n_dream) if n_dream else []
        dream_samples = [self._dream_sample(s, dream_length) for s in dream_seeds]

        samples = real_samples + dream_samples
        self._rng.shuffle(samples)

        z0 = torch.tensor([s.z0 for s in samples], dtype=torch.float32)
        actions_by_key = {
            key: index for index, key in enumerate(self.dream_cortex.action_keys)
        }
        actions = torch.tensor(
            [[actions_by_key[a] for a in s.actions] for s in samples], dtype=torch.long,
        )
        targets = torch.stack([s.targets for s in samples], dim=0)

        return TrainingBatch(
            z0=z0, actions=actions, targets=targets,
            n_real=n_real, n_dream=n_dream, fraction_requested=fraction,
        )
