"""Model Factory: reproducible checkpoint lineage and budgeted experiments.

Phase A (issue #213) adds the contract dataclasses and canonical hashing
primitive that every later phase's ``run_id``, ``architecture_hash``,
``data_contract_hash``, ``training_contract_hash``, and
``parent_checkpoint_sha`` identities are derived from. Phase A, step 2
(issue #214) adds ``ExperimentSpec``: the immutable, fully-resolved
description of one trial. See epic #212.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from cognitive_runtime.training.model_factory.contracts import (
    ArchitectureContract,
    DataContract,
    ExecutionProvenance,
    TrainingContract,
    canonical_json,
    contract_hash,
)
from cognitive_runtime.training.model_factory.spec import (
    DEFAULT_SPEC,
    DOCUMENT_FORMAT,
    VALID_MODES,
    ExperimentSpec,
    SpecError,
    apply_overrides,
    dump_canonical_json,
    load_spec,
    resolve,
    validate,
)
from cognitive_runtime.training.model_factory.artifacts import (
    CONTRACTS_FORMAT,
    DATA_MANIFEST_FORMAT,
    EXECUTION_FORMAT,
    EXPERIMENT_IDENTITY_FORMAT,
    LINEAGE_FORMAT,
    RunArtifacts,
    allocate_run_artifacts,
    atomic_write_json,
    execution_manifest,
)
from cognitive_runtime.training.model_factory.naming import (
    DISPLAY_NAME_FORMAT,
    DisplayNameAssignment,
    DisplayNameParent,
    assign_display_name,
    load_display_name,
    new_naming_seed,
    surname_sequence,
)
from cognitive_runtime.training.model_factory.checkpoint import (
    FORMAT as FACTORY_CHECKPOINT_FORMAT,
    HEADER_FORMAT as FACTORY_CHECKPOINT_HEADER_FORMAT,
    ContinuationDecision,
    ContinuationMismatch,
    FactoryCheckpoint,
    capture_rng_state,
    factory_checkpoint_metadata_path,
    load_factory_checkpoint,
    read_factory_checkpoint_metadata,
    restore_rng_state,
    save_factory_checkpoint,
    validate_continuation,
)
from cognitive_runtime.training.model_factory.budget import (
    BUDGET_REPORT_FORMAT,
    BUDGET_TIERS,
    COMPLETION_STATUSES,
    STATUS_BUDGET_EXCEEDED,
    STATUS_COMPLETED,
    STATUS_TIMEOUT_UNRECOVERABLE,
    TIMING_POLICY_VERSION,
    BudgetDecision,
    EpochTimer,
    TrainingBudget,
    budget_seconds_for_tier,
    build_budget_report,
    watchdog_expired,
    write_budget_report,
)
from cognitive_runtime.training.model_factory.state import (
    ACTIVE_STATES,
    ALL_STATES,
    DEVICE_LEDGER_FORMAT,
    HEARTBEAT_FORMAT,
    STATE_BUDGET_EXCEEDED,
    STATE_CANCELLED,
    STATE_CHECKPOINTING,
    STATE_COMPLETED,
    STATE_FAILED,
    STATE_FORMAT,
    STATE_QUEUED,
    STATE_RUNNING,
    TERMINAL_STATES,
    DeviceReservationError,
    IllegalTransitionError,
    IncompleteRunError,
    StateError,
    TrialState,
    create_state,
    heartbeat_age_seconds,
    heartbeat_path,
    is_stale,
    load_state,
    recover_stale_worker,
    release_devices,
    require_completed_for_promotion,
    reserve_devices,
    retry_failed_run,
    state_path,
    transition,
    write_heartbeat,
)
from cognitive_runtime.training.model_factory.comparison import (
    COMPARISON_FORMAT,
    DEFAULT_CONFIDENCE as COMPARISON_DEFAULT_CONFIDENCE,
    DEFAULT_MIN_EPISODE_COUNT,
    DEFAULT_RESAMPLES,
    PairedComparison,
    compare_paired,
    compare_paired_episodes,
    paired_bootstrap_interval,
    paired_permutation_interval,
)
from cognitive_runtime.training.model_factory.genome import (
    GENE_TYPES,
    GENOME_SCHEMAS,
    GENERIC_ACTION_EFFECTS_V1,
    GENERIC_ACTION_EFFECTS_V2,
    MUTATION_DISTRIBUTIONS,
    OBJECTIVES,
    Gene,
    GenomeRepairError,
    GenomeSchema,
    GenomeSchemaError,
    MutationSpec,
    build_schema,
    crossover,
    default_genome,
    get_schema,
    mutate,
    project_cost_seconds,
    repair,
    sample_genome,
)
from cognitive_runtime.training.model_factory.search import (
    EVOLUTIONARY_SEARCH_FORMAT,
    METHODS as SEARCH_METHODS,
    EvolutionCandidateResult,
    EvolutionarySearchReport,
    PopulationReport,
    RungCandidateResult,
    RungReport,
    SearchError,
    SuccessiveHalvingReport,
    propose,
    run_evolutionary_search,
    run_successive_halving,
)
from cognitive_runtime.training.model_factory.breeding import (
    BreedingError,
    BreedingLineage,
    BreedingResult,
    ParentRecord,
    breed,
    check_compatible,
    load_parent,
    record_breeding_lineage,
    select_weight_donor,
)
from cognitive_runtime.training.model_factory.population import (
    POPULATION_POLICY_FORMAT,
    ComputeLedger,
    DuplicateSpecCache,
    PopulationCandidate,
    PopulationDecision,
    PopulationError,
    PopulationPolicy,
    configuration_distance,
    dominates,
    replace_population,
    resolved_spec_fingerprint,
    select_parents,
)
from cognitive_runtime.training.model_factory.registry import (
    DECISION_HOLD,
    DECISION_PROMOTE,
    DECISION_TEST_USE,
    LINEAGE_MANIFEST_NAME,
    REGISTRY_FORMAT,
    ChampionEntry,
    LineageCycleError,
    LineageGraph,
    LineageNode,
    RegistryError,
    RegistrySlot,
    hold,
    leading_champion,
    lineage_graph,
    population,
    promote,
    record_test_use,
    registry_path,
)
if TYPE_CHECKING:
    from cognitive_runtime.training.model_factory.corpus import (
        CORPUS_MANIFEST_FORMAT,
        CORPUS_SPEC_FORMAT,
        DEFAULT_SPLIT_ROLES,
        QUALITY_REPORT_FORMAT,
        SPLIT_OVERLAP_REPORT_FORMAT,
        ResolvedCorpus,
        build_corpus,
        load_corpus_spec,
        resolve_corpus,
    )
    from cognitive_runtime.training.model_factory.runner import (
        DEFAULT_EPOCH_BUDGET,
        RUNS_ROOT_DEFAULT,
        TrialResult,
        run_trial,
    )

__all__ = [
    "ArchitectureContract",
    "DataContract",
    "ExecutionProvenance",
    "TrainingContract",
    "canonical_json",
    "contract_hash",
    "DEFAULT_SPEC",
    "DOCUMENT_FORMAT",
    "VALID_MODES",
    "ExperimentSpec",
    "SpecError",
    "apply_overrides",
    "dump_canonical_json",
    "load_spec",
    "resolve",
    "validate",
    "EXPERIMENT_IDENTITY_FORMAT",
    "CONTRACTS_FORMAT",
    "LINEAGE_FORMAT",
    "EXECUTION_FORMAT",
    "DATA_MANIFEST_FORMAT",
    "RunArtifacts",
    "atomic_write_json",
    "execution_manifest",
    "allocate_run_artifacts",
    "DISPLAY_NAME_FORMAT",
    "DisplayNameAssignment",
    "DisplayNameParent",
    "assign_display_name",
    "load_display_name",
    "new_naming_seed",
    "surname_sequence",
    "FACTORY_CHECKPOINT_FORMAT",
    "FACTORY_CHECKPOINT_HEADER_FORMAT",
    "ContinuationDecision",
    "ContinuationMismatch",
    "FactoryCheckpoint",
    "capture_rng_state",
    "factory_checkpoint_metadata_path",
    "read_factory_checkpoint_metadata",
    "restore_rng_state",
    "save_factory_checkpoint",
    "load_factory_checkpoint",
    "validate_continuation",
    "BUDGET_REPORT_FORMAT",
    "BUDGET_TIERS",
    "COMPLETION_STATUSES",
    "STATUS_BUDGET_EXCEEDED",
    "STATUS_COMPLETED",
    "STATUS_TIMEOUT_UNRECOVERABLE",
    "TIMING_POLICY_VERSION",
    "BudgetDecision",
    "EpochTimer",
    "TrainingBudget",
    "budget_seconds_for_tier",
    "build_budget_report",
    "watchdog_expired",
    "write_budget_report",
    "CORPUS_SPEC_FORMAT",
    "CORPUS_MANIFEST_FORMAT",
    "DEFAULT_SPLIT_ROLES",
    "QUALITY_REPORT_FORMAT",
    "SPLIT_OVERLAP_REPORT_FORMAT",
    "ResolvedCorpus",
    "build_corpus",
    "load_corpus_spec",
    "resolve_corpus",
    "STATE_FORMAT",
    "HEARTBEAT_FORMAT",
    "DEVICE_LEDGER_FORMAT",
    "STATE_QUEUED",
    "STATE_RUNNING",
    "STATE_CHECKPOINTING",
    "STATE_COMPLETED",
    "STATE_BUDGET_EXCEEDED",
    "STATE_FAILED",
    "STATE_CANCELLED",
    "ALL_STATES",
    "ACTIVE_STATES",
    "TERMINAL_STATES",
    "StateError",
    "IllegalTransitionError",
    "IncompleteRunError",
    "DeviceReservationError",
    "TrialState",
    "state_path",
    "heartbeat_path",
    "load_state",
    "create_state",
    "transition",
    "write_heartbeat",
    "heartbeat_age_seconds",
    "is_stale",
    "recover_stale_worker",
    "require_completed_for_promotion",
    "retry_failed_run",
    "reserve_devices",
    "release_devices",
    "COMPARISON_FORMAT",
    "COMPARISON_DEFAULT_CONFIDENCE",
    "DEFAULT_MIN_EPISODE_COUNT",
    "DEFAULT_RESAMPLES",
    "PairedComparison",
    "compare_paired",
    "compare_paired_episodes",
    "paired_bootstrap_interval",
    "paired_permutation_interval",
    "REGISTRY_FORMAT",
    "LINEAGE_MANIFEST_NAME",
    "DECISION_PROMOTE",
    "DECISION_HOLD",
    "DECISION_TEST_USE",
    "RegistryError",
    "LineageCycleError",
    "ChampionEntry",
    "RegistrySlot",
    "LineageNode",
    "LineageGraph",
    "registry_path",
    "promote",
    "hold",
    "leading_champion",
    "population",
    "record_test_use",
    "lineage_graph",
    "DEFAULT_EPOCH_BUDGET",
    "RUNS_ROOT_DEFAULT",
    "TrialResult",
    "run_trial",
    "GENE_TYPES",
    "GENOME_SCHEMAS",
    "GENERIC_ACTION_EFFECTS_V1",
    "MUTATION_DISTRIBUTIONS",
    "OBJECTIVES",
    "Gene",
    "GenomeRepairError",
    "GenomeSchema",
    "GenomeSchemaError",
    "MutationSpec",
    "build_schema",
    "crossover",
    "default_genome",
    "get_schema",
    "mutate",
    "project_cost_seconds",
    "repair",
    "sample_genome",
    "SEARCH_METHODS",
    "SearchError",
    "EVOLUTIONARY_SEARCH_FORMAT",
    "EvolutionCandidateResult",
    "PopulationReport",
    "EvolutionarySearchReport",
    "RungCandidateResult",
    "RungReport",
    "SuccessiveHalvingReport",
    "propose",
    "run_evolutionary_search",
    "run_successive_halving",
    "BreedingError",
    "BreedingLineage",
    "BreedingResult",
    "ParentRecord",
    "breed",
    "check_compatible",
    "load_parent",
    "record_breeding_lineage",
    "select_weight_donor",
    "POPULATION_POLICY_FORMAT",
    "PopulationError",
    "ComputeLedger",
    "PopulationCandidate",
    "PopulationPolicy",
    "PopulationDecision",
    "configuration_distance",
    "dominates",
    "replace_population",
    "resolved_spec_fingerprint",
    "DuplicateSpecCache",
    "select_parents",
]


_LAZY_CORPUS_EXPORTS = {
    "CORPUS_SPEC_FORMAT",
    "CORPUS_MANIFEST_FORMAT",
    "DEFAULT_SPLIT_ROLES",
    "QUALITY_REPORT_FORMAT",
    "SPLIT_OVERLAP_REPORT_FORMAT",
    "ResolvedCorpus",
    "build_corpus",
    "load_corpus_spec",
    "resolve_corpus",
}

#: run_trial() always needs torch to do real work, so -- like the corpus
#: module -- it is exported lazily to keep `import
#: cognitive_runtime.training.model_factory` itself usable in the core-only
#: install (issue #225).
_LAZY_RUNNER_EXPORTS = {
    "DEFAULT_EPOCH_BUDGET",
    "RUNS_ROOT_DEFAULT",
    "TrialResult",
    "run_trial",
}


def __getattr__(name: str):
    """Keep the existing core-only Model Factory import boundary torch-free."""
    if name in _LAZY_CORPUS_EXPORTS:
        from cognitive_runtime.training.model_factory import corpus

        return getattr(corpus, name)
    if name in _LAZY_RUNNER_EXPORTS:
        from cognitive_runtime.training.model_factory import runner

        return getattr(runner, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
